version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: tutorwise-neo4j 
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: tutorwise-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  backend:
    build: 
      context: ./ai-backend 
      dockerfile: Dockerfile
    container_name: tutorwise-backend
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password123
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    depends_on:
      - neo4j
      - redis
    volumes:
      - ./ai-backend:/app
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
  redis_data: