#!/bin/bash

##############################################################################
# TutorWise Shell Aliases Setup
#
# This script creates shell aliases for cas-startup and other frequently
# used commands, allowing users to type short commands instead of full
# "npm run" commands.
#
# Usage:
#   bash tools/scripts/setup-aliases.sh
#
# This will add aliases to your shell configuration file (.zshrc or .bashrc)
##############################################################################

set -e

# Determine the user's shell configuration file
if [ -n "$ZSH_VERSION" ]; then
    SHELL_CONFIG="$HOME/.zshrc"
    SHELL_NAME="zsh"
elif [ -n "$BASH_VERSION" ]; then
    SHELL_CONFIG="$HOME/.bashrc"
    SHELL_NAME="bash"
else
    echo "⚠️  Unable to detect shell type. Defaulting to .bashrc"
    SHELL_CONFIG="$HOME/.bashrc"
    SHELL_NAME="unknown"
fi

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

echo "🔧 TutorWise Shell Aliases Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Shell detected: $SHELL_NAME"
echo "Config file: $SHELL_CONFIG"
echo ""

# Create backup of shell config
if [ -f "$SHELL_CONFIG" ]; then
    cp "$SHELL_CONFIG" "${SHELL_CONFIG}.backup.$(date +%Y%m%d_%H%M%S)"
    echo "✅ Created backup of $SHELL_CONFIG"
fi

# Check if aliases already exist
if grep -q "# TutorWise CAS Aliases" "$SHELL_CONFIG" 2>/dev/null; then
    echo "⚠️  TutorWise aliases already exist in $SHELL_CONFIG"
    echo ""
    read -p "Do you want to update them? (y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled"
        exit 0
    fi

    # Remove old aliases
    sed -i.tmp '/# TutorWise CAS Aliases/,/# End TutorWise CAS Aliases/d' "$SHELL_CONFIG"
    rm -f "${SHELL_CONFIG}.tmp"
    echo "✅ Removed old aliases"
fi

# Append new aliases
cat >> "$SHELL_CONFIG" << 'EOF'

# ============================================================================
# TutorWise CAS Aliases
# Auto-generated by tools/scripts/setup-aliases.sh
# ============================================================================

# CAS Startup Utility
alias cas-startup='npm run cas-startup'
alias cas-status='npm run cas-startup:status'
alias cas-start='npm run cas-startup:start-all'
alias cas-stop='npm run cas-startup:stop-all'
alias cas-restart='npm run cas-startup:restart-all'

# Development Servers
alias dev-web='npm run dev:web'
alias dev-api='npm run dev:api'
alias dev-all='npm run dev'

# Jira Integration
alias jira-test='npm run jira:test-tasks'
alias jira-poll='npm run jira:poll:continuous'

# Calendar Integration
alias calendar-test='npm run calendar:test-tasks'
alias calendar-poll='npm run calendar:poll:continuous'

# Sync Commands
alias sync-jira='npm run sync:jira'
alias sync-github='npm run sync:github'
alias sync-context='npm run sync:context'
alias sync-confluence='npm run sync:confluence'
alias sync-google-docs='npm run sync:google-docs'
alias sync-calendar-jira='npm run sync:calendar-to-jira:continuous'

# CAS (Context Autonomous System)
alias cas-generate='npm run cas:generate'
alias cas-setup='npm run context:setup'

# Testing
alias test-web='npm run test'
alias test-api='npm run test:backend'
alias test-e2e='npm run test:e2e'
alias test-integrations='node tools/scripts/utilities/test-integrations.js'

# Build & Deploy
alias build-web='npm run build'
alias deploy-railway='npm run deploy:railway'
alias deploy-vercel='npm run deploy:vercel'
alias deploy-vercel-prod='npm run deploy:vercel:prod'

# Health & Monitoring
alias health-check='bash tools/scripts/health-check.sh'

# Claude Code
alias claude-login='npm run claude:login'

# End TutorWise CAS Aliases
# ============================================================================
EOF

echo ""
echo "✅ Aliases added to $SHELL_CONFIG"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Available Aliases:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "CAS Startup:"
echo "  cas-startup       → Interactive startup manager"
echo "  cas-status        → Show all service statuses"
echo "  cas-start         → Start all services"
echo "  cas-stop          → Stop all services"
echo "  cas-restart       → Restart all services"
echo ""
echo "Development:"
echo "  dev-web           → Start Next.js frontend"
echo "  dev-api           → Start FastAPI backend"
echo "  dev-all           → Start both servers"
echo ""
echo "Integrations:"
echo "  jira-test         → Test Jira connection"
echo "  jira-poll         → Start Jira polling"
echo "  calendar-test     → Test Google Calendar"
echo "  calendar-poll     → Start Calendar polling"
echo ""
echo "Sync:"
echo "  sync-jira         → Sync with Jira"
echo "  sync-github       → Sync with GitHub"
echo "  sync-confluence   → Sync to Confluence"
echo "  sync-google-docs  → Sync to Google Docs"
echo ""
echo "Testing:"
echo "  test-web          → Run frontend tests"
echo "  test-api          → Run backend tests"
echo "  test-e2e          → Run E2E tests"
echo "  test-integrations → Test all integrations"
echo ""
echo "Other:"
echo "  health-check      → Run system health check"
echo "  cas-generate      → Generate AI context"
echo "  claude-login      → Initialize Claude Code session"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚡ To activate aliases, run:"
echo "   source $SHELL_CONFIG"
echo ""
echo "   Or restart your terminal"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
