-- Migration: 034_add_listing_commission_delegation.sql
-- Purpose: Add commission delegation column to listings table (SDD v4.3, Section 4.1)
-- Date: 2025-11-06
-- Prerequisites: profiles and listings tables exist, connections table created
--
-- This migration enables the "Tutor-Led" referral model where a tutor (Jane) can
-- delegate the referral commission from a specific listing to a connected agent (Bob).
-- This solves the "brochure in 50 stores" use case.

-- Add delegation column to listings table
ALTER TABLE public.listings
ADD COLUMN IF NOT EXISTS delegate_commission_to_profile_id UUID
  REFERENCES public.profiles(id)
  ON DELETE SET NULL;

-- Create index for fast lookups when processing payments
CREATE INDEX IF NOT EXISTS idx_listings_delegate_commission_to
ON public.listings(delegate_commission_to_profile_id)
WHERE delegate_commission_to_profile_id IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN public.listings.delegate_commission_to_profile_id IS
'[SDD v4.3] The profile ID of the user (typically an Agent) who should receive any referral commissions generated by this specific listing. If NULL, the listing owner (Tutor) receives the commission. This enables the "Tutor-Led" offline referral model where Jane can print one QR code but delegate commissions to her agent partner Bob.';

-- Add constraint to ensure delegated user exists and is different from listing owner
-- Note: We allow delegation to self (null constraint) as it's equivalent to no delegation
ALTER TABLE public.listings
ADD CONSTRAINT check_delegation_not_self
CHECK (
  delegate_commission_to_profile_id IS NULL OR
  delegate_commission_to_profile_id != profile_id
);

-- Migration rollback (for reference, commented out)
-- ALTER TABLE public.listings DROP COLUMN IF EXISTS delegate_commission_to_profile_id;
-- DROP INDEX IF EXISTS idx_listings_delegate_commission_to;
