-- CAS Analyst Reports Table
-- Migration: 274_create_cas_analyst_reports.sql
--
-- Creates table for analytical reports generated by CAS Feedback Processor
-- Reports are reviewed by CAS Analyst agent for deeper investigation

-- ============================================
-- CAS ANALYST REPORTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS cas_analyst_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Report metadata
    report_type TEXT NOT NULL CHECK (report_type IN (
        'feedback_pattern',     -- Analysis of feedback patterns
        'user_satisfaction',    -- Satisfaction trend analysis
        'topic_performance',    -- Subject/topic performance review
        'agent_comparison',     -- Sage vs Lexi performance
        'engagement_trend',     -- User engagement analysis
        'error_analysis',       -- Error pattern analysis
        'weekly_summary'        -- Weekly metrics summary
    )),
    title TEXT NOT NULL,
    summary TEXT NOT NULL,

    -- Analysis details
    agent_scope TEXT CHECK (agent_scope IN ('sage', 'lexi', 'both')),
    time_period_start TIMESTAMPTZ NOT NULL,
    time_period_end TIMESTAMPTZ NOT NULL,

    -- Metrics and findings
    metrics JSONB NOT NULL DEFAULT '{}',  -- Key performance metrics
    findings JSONB NOT NULL DEFAULT '[]', -- Array of finding objects
    recommendations JSONB NOT NULL DEFAULT '[]', -- Array of recommendation objects

    -- Data sources
    data_sources JSONB NOT NULL DEFAULT '{}', -- Session counts, feedback counts, etc.
    sample_feedback_ids UUID[] DEFAULT '{}',  -- Sample feedback entries analyzed

    -- Severity and impact
    severity TEXT CHECK (severity IN ('critical', 'high', 'medium', 'low', 'info')),
    estimated_impact TEXT CHECK (estimated_impact IN ('high', 'medium', 'low')),
    affected_users_count INTEGER DEFAULT 0,

    -- Review status
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN (
        'pending',      -- Awaiting CAS Analyst review
        'reviewed',     -- Reviewed by Analyst
        'actioned',     -- Actions taken
        'archived'      -- Archived for reference
    )),
    reviewed_at TIMESTAMPTZ,
    reviewed_by TEXT,
    action_notes TEXT,

    -- Related tasks
    related_planner_tasks UUID[] DEFAULT '{}', -- Links to cas_planner_tasks

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- INDEXES
-- ============================================
CREATE INDEX IF NOT EXISTS idx_cas_analyst_reports_report_type ON cas_analyst_reports(report_type);
CREATE INDEX IF NOT EXISTS idx_cas_analyst_reports_agent_scope ON cas_analyst_reports(agent_scope);
CREATE INDEX IF NOT EXISTS idx_cas_analyst_reports_severity ON cas_analyst_reports(severity);
CREATE INDEX IF NOT EXISTS idx_cas_analyst_reports_status ON cas_analyst_reports(status);
CREATE INDEX IF NOT EXISTS idx_cas_analyst_reports_created_at ON cas_analyst_reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cas_analyst_reports_time_period ON cas_analyst_reports(time_period_end DESC);

-- Combined index for dashboard queries
CREATE INDEX IF NOT EXISTS idx_cas_analyst_reports_dashboard
    ON cas_analyst_reports(status, severity, created_at DESC);

-- GIN index for JSONB queries
CREATE INDEX IF NOT EXISTS idx_cas_analyst_reports_metrics ON cas_analyst_reports USING GIN(metrics);
CREATE INDEX IF NOT EXISTS idx_cas_analyst_reports_findings ON cas_analyst_reports USING GIN(findings);

-- ============================================
-- TRIGGERS
-- ============================================
CREATE OR REPLACE FUNCTION update_cas_analyst_reports_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();

    -- Auto-set reviewed_at when status changes to reviewed
    IF NEW.status IN ('reviewed', 'actioned') AND OLD.status = 'pending' THEN
        NEW.reviewed_at = NOW();
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_cas_analyst_reports_updated_at ON cas_analyst_reports;
CREATE TRIGGER trigger_update_cas_analyst_reports_updated_at
    BEFORE UPDATE ON cas_analyst_reports
    FOR EACH ROW
    EXECUTE FUNCTION update_cas_analyst_reports_updated_at();

-- ============================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================
ALTER TABLE cas_analyst_reports ENABLE ROW LEVEL SECURITY;

-- ============================================
-- RLS POLICIES
-- ============================================
-- Admins can read all reports
DROP POLICY IF EXISTS "Admins can read analyst reports" ON cas_analyst_reports;
CREATE POLICY "Admins can read analyst reports" ON cas_analyst_reports
    FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
            AND 'admin' = ANY(profiles.roles)
        )
    );

-- Admins can update reports
DROP POLICY IF EXISTS "Admins can update analyst reports" ON cas_analyst_reports;
CREATE POLICY "Admins can update analyst reports" ON cas_analyst_reports
    FOR UPDATE TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
            AND 'admin' = ANY(profiles.roles)
        )
    );

-- Service role full access
DROP POLICY IF EXISTS "Service role full access to analyst reports" ON cas_analyst_reports;
CREATE POLICY "Service role full access to analyst reports" ON cas_analyst_reports
    FOR ALL USING (auth.jwt()->>'role' = 'service_role');

-- ============================================
-- COMMENTS
-- ============================================
COMMENT ON TABLE cas_analyst_reports IS 'Analytical reports generated by CAS Feedback Processor for CAS Analyst review';
COMMENT ON COLUMN cas_analyst_reports.metrics IS 'JSON object with key metrics: avgRating, satisfactionRate, responseTime, etc.';
COMMENT ON COLUMN cas_analyst_reports.findings IS 'Array of finding objects: {type, severity, description, affectedCount}';
COMMENT ON COLUMN cas_analyst_reports.recommendations IS 'Array of recommendation objects: {priority, action, expectedImpact}';
COMMENT ON COLUMN cas_analyst_reports.data_sources IS 'Metadata about data analyzed: sessionCount, feedbackCount, dateRange, etc.';
COMMENT ON COLUMN cas_analyst_reports.related_planner_tasks IS 'Array of cas_planner_tasks.id that were created from this report';
