/**
 * Migration: 316_add_cas_metrics_to_platform_statistics.sql
 * Purpose: Add CAS AI Agents metrics columns to platform_statistics_daily table
 * Created: 2026-02-26
 *
 * Adds columns for CAS trend charts:
 * - cas_tasks_generated: Total tasks generated by all agents
 * - cas_insights_created: Total insights created by agents
 */

-- Add CAS metrics columns to platform_statistics_daily
ALTER TABLE platform_statistics_daily
  ADD COLUMN IF NOT EXISTS cas_tasks_generated INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cas_insights_created INTEGER DEFAULT 0;

-- Add comments
COMMENT ON COLUMN platform_statistics_daily.cas_tasks_generated IS 'Total tasks generated by CAS agents (daily snapshot)';
COMMENT ON COLUMN platform_statistics_daily.cas_insights_created IS 'Total insights created by CAS agents (daily snapshot)';

-- Initialize with zeros for existing rows
UPDATE platform_statistics_daily
SET
  cas_tasks_generated = COALESCE(cas_tasks_generated, 0),
  cas_insights_created = COALESCE(cas_insights_created, 0)
WHERE
  cas_tasks_generated IS NULL
  OR cas_insights_created IS NULL;
