-- Migration 318: ai_agents table consolidation (SUPERSEDED)
--
-- STATUS: This migration was documentation-only. The actual rename was
-- completed in migration 319_rename_ai_tutor_tables_to_ai_agent.sql which:
--
--   1. Dropped the empty ai_tutors table
--   2. Renamed all 12 child tables: ai_tutor_* → ai_agent_*
--   3. Renamed/dropped columns: ai_tutor_id → agent_id
--   4. Renamed all indexes, functions, triggers, RLS policies
--   5. Created backward-compat wrapper for check_ai_tutor_limit
--
-- All code now uses ai_agent_* table names and agent_id column.
-- See migration 319 for the complete rename implementation.
