-- STUB: Migration 345 — Growth Score table
-- Status: Table was created in migration 366 (retention_platform_metrics_daily)
--         alongside the retention compute function. Column is 'role' (not 'role_type').
-- See: tools/database/migrations/366_retention_platform_metrics_daily.sql
-- See: conductor/conductor-growth-score-all-roles.md
