-- RESERVED: Migration 346
-- Phase: iPOM v3.4 — Phase 1 production fixes
-- Description: Phase 1 process execution engine production hardening fixes
-- Spec: ipom/process-execution-solution-design.md
-- Status: Pending implementation
