-- REASSIGNED: Migration 354
-- Phase: Conductor Phase 3 — Referral Intelligence
-- REASSIGNED TO: Migration 365 (referral_network_stats materialized view)
-- See: conductor/referral-intelligence-spec.md
-- Note: Referral network stats materialized view has been correctly assigned to migration 365.
