-- Migration 424: AI post-session report storage
-- Stores structured JSON report generated by Sage after each session

ALTER TABLE virtualspace_sessions
  ADD COLUMN IF NOT EXISTS session_report JSONB;

-- Index for report presence queries (e.g. show "View Report" badge)
CREATE INDEX IF NOT EXISTS idx_virtualspace_sessions_has_report
  ON virtualspace_sessions ((session_report IS NOT NULL));
