-- Migration 429: Seed 5 built-in Learn Your Way workflows

INSERT INTO session_workflows (slug, name, description, short_description, theme, tags, exam_board, subject, level, duration_mins, ai_involvement, sen_focus, phases, learn_your_way, built_in, published) VALUES

-- 1. Treasure Map Ratio Raid
('treasure-map-ratio-raid',
 'Treasure Map Ratio Raid',
 'A pirate adventure through ratio and proportion. Divide the treasure, master the map scale, and prove you''re a true pirate mathematician.',
 'Divide the treasure — master ratio & proportion with Captain Sage',
 '{"icon":"🏴‍☠️","colour":"#c2860a","backgroundStyle":"dotted","narrative":"Captain Sage has discovered a legendary treasure chest. But the crew can''t agree on how to split the gold fairly. Only a student who masters ratio and proportion can save the voyage — and claim the biggest share."}',
 ARRAY['maths','ratio','proportion','11+','gcse','foundation','year-7','year-8'],
 'any', 'maths', 'foundation', 45, 'full', false,
 '[
   {"id":"warm-up","name":"Treasure Hunt Warm-Up","icon":"🗺️","durationMins":5,"sageMode":"full","sagePersona":"You are Captain Sage, a wise and encouraging pirate navigator. You speak with warmth and adventure. Every maths concept is a new sea to navigate. Keep explanations short, vivid, and tied to the treasure story.","sagePromptTemplate":"Start with 3 quick mental maths questions framed as dividing gold coins: ''If 12 coins are shared between 3 pirates, how many each?'' Scale up to ratio notation. Praise every answer. If wrong, say ''The sea is tricky — let me show you the map.''","canvasActions":[{"type":"set_background","backgroundStyle":"dotted"},{"type":"stamp_shape","shape":"number-line","position":"center"}],"exitConditions":{"timeExpiredMins":5,"tutorOverride":true},"narrative":"A quick warm-up to get your maths brain ready. Divide the first haul of coins!"},
   {"id":"instruction","name":"The Ratio Map","icon":"📜","durationMins":12,"sageMode":"full","sagePersona":"You are Captain Sage. You are now teaching the student to read the treasure map — which is really a ratio problem. Use the fraction bar tool on the canvas to show splitting.","sagePromptTemplate":"Teach ratio notation (a:b), simplifying ratios, and dividing quantities in a given ratio. Use the fraction bar shape on the canvas. Tie every example to dividing treasure, crew shares, map scales. Check for understanding after each concept before moving on.","canvasActions":[{"type":"clear_canvas"},{"type":"stamp_shape","shape":"fraction-bar","position":"center"},{"type":"add_text","props":{"text":"Ratio = fair shares 🏴‍☠️","position":"top-left"}}],"exitConditions":{"timeExpiredMins":15,"tutorOverride":true,"sageSuggestsReady":true},"narrative":"Captain Sage reveals the secrets of the ratio map. Pay attention — the treasure depends on it!"},
   {"id":"practice","name":"Claim Your Share","icon":"⚔️","durationMins":15,"sageMode":"hints","sagePromptTemplate":"Give the student 4 ratio problems of increasing difficulty. Do NOT solve them. Give one-sentence hints only if the student asks or is stuck for >60 seconds. Celebrate each correct answer with a pirate reference. After each question, briefly explain the method.","canvasActions":[{"type":"clear_canvas"},{"type":"stamp_shape","shape":"fraction-bar","position":"top-left"}],"exitConditions":{"minMasteryScore":60,"timeExpiredMins":18,"tutorOverride":true},"narrative":"Time to claim your share! Solve the ratio challenges and prove you''re a true pirate mathematician."},
   {"id":"assessment","name":"The Final Chest","icon":"🪙","durationMins":8,"sageMode":"silent","sagePromptTemplate":"Present 2 exam-style ratio questions. Do NOT help at all. When complete, reveal correct answers and mark each step. Give a mastery score out of 100. Identify one strength and one area to practise.","canvasActions":[{"type":"clear_canvas"},{"type":"add_text","props":{"text":"Final Challenge 🪙 — no hints this time!","position":"top-left"}}],"exitConditions":{"timeExpiredMins":10,"tutorOverride":true},"narrative":"The final chest is locked. Only your own knowledge can open it — no hints!","homeworkEnabled":true},
   {"id":"recap","name":"Voyage Complete","icon":"🏆","durationMins":5,"sageMode":"full","sagePromptTemplate":"Summarise what was covered: ratio notation, simplifying, dividing quantities. Highlight 1–2 things the student did well and 1–2 things to practise. Suggest a homework task. Frame it as: ''You''ve navigated these seas well, sailor — here''s your next voyage.''","canvasActions":[],"exitConditions":{"tutorOverride":true,"timeExpiredMins":5},"narrative":"Voyage complete! Captain Sage summarises your journey and prepares you for the next adventure."}
 ]'::jsonb,
 '{"freedoms":["style","ai_involvement","support"],"agencyPoints":["Choose how much Sage hints during practice","Skip the warm-up if you already know your basics","Tutor can pause Sage and take over at any point"],"bestFor":"Students who love storytelling and want maths to feel like an adventure"}',
 true, true),

-- 2. Quadratics — Alien Invasion
('quadratics-alien-invasion',
 'Quadratics — Alien Invasion',
 'An alien fleet has locked onto Earth. Only quadratic equations can stop them. GCSE Higher exam technique + surds, sci-fi style.',
 'Defeat the alien fleet using quadratic equations — GCSE Higher',
 '{"icon":"👾","colour":"#6366f1","backgroundStyle":"dark","narrative":"An alien fleet has locked onto Earth''s coordinates. The only weapon that can stop them? Quadratic equations. Each solved problem destroys a ship. Sage is your tactical AI — but you have to fire the equations yourself."}',
 ARRAY['maths','quadratics','algebra','graphs','gcse','higher','year-10','year-11','exam-technique'],
 'any', 'maths', 'higher', 50, 'hints', false,
 '[
   {"id":"mission-brief","name":"Mission Brief","icon":"📡","durationMins":3,"sageMode":"full","sagePersona":"You are Tactical AI Sage, a calm and precise military intelligence system. Use precise language. Every quadratic concept is a targeting system component.","sagePromptTemplate":"Quickly recap: factorising, completing the square, quadratic formula, and graph sketching. One sentence each. Ask the student which feels weakest — that''s where we focus.","canvasActions":[{"type":"set_background","backgroundStyle":"dark"},{"type":"add_text","props":{"text":"👾 ALIEN INVASION — TARGETING SYSTEMS ONLINE","position":"top-left"}}],"exitConditions":{"timeExpiredMins":4,"tutorOverride":true},"narrative":"Tactical briefing — know your weapons before the fleet arrives."},
   {"id":"factorising","name":"Destroy Fleet Alpha — Factorising","icon":"🚀","durationMins":12,"sageMode":"hints","sagePromptTemplate":"Give 3 factorising questions (simple → difference of squares → harder trinomials). Hint only: ''What two numbers multiply to give c and add to give b?'' Show method on canvas after each answer. Exam tip: always check by expanding.","canvasActions":[{"type":"clear_canvas"},{"type":"stamp_shape","shape":"latex-equation","position":"center"}],"exitConditions":{"minMasteryScore":70,"timeExpiredMins":15,"tutorOverride":true},"narrative":"Fleet Alpha uses factorised quadratics as a shield. Break through it."},
   {"id":"graphs","name":"Map the Fleet — Quadratic Graphs","icon":"📈","durationMins":12,"sageMode":"hints","sagePromptTemplate":"Sketch y = x² - 5x + 6 on the function plotter. Ask student to identify roots, vertex, y-intercept. Then give one transformation. Hint only if stuck >90s.","canvasActions":[{"type":"clear_canvas"},{"type":"stamp_shape","shape":"function-plotter","position":"center"}],"exitConditions":{"minMasteryScore":65,"timeExpiredMins":15,"tutorOverride":true},"narrative":"Plot the trajectory of the alien ships — they follow quadratic paths."},
   {"id":"exam-practice","name":"Final Strike — Exam Questions","icon":"💥","durationMins":18,"sageMode":"silent","sagePromptTemplate":"Present 2 full GCSE Higher exam questions on quadratics (one algebraic, one graphical). Timed. No help. After both done, mark each step — identify method marks vs accuracy marks. Give exam technique tip.","canvasActions":[{"type":"clear_canvas"},{"type":"add_text","props":{"text":"FINAL STRIKE — exam conditions. No hints. 18 minutes.","position":"top-left"}}],"exitConditions":{"timeExpiredMins":20,"tutorOverride":true},"narrative":"Exam conditions. One shot to destroy the command ship.","homeworkEnabled":true},
   {"id":"debrief","name":"Mission Debrief","icon":"🏅","durationMins":5,"sageMode":"full","sagePromptTemplate":"Give mastery score. Identify strongest and weakest method. Recommend one specific homework. Frame as mission debrief.","canvasActions":[],"exitConditions":{"timeExpiredMins":5,"tutorOverride":true},"narrative":"Mission debrief — what worked, what to sharpen before the next invasion."}
 ]'::jsonb,
 '{"freedoms":["goal","ai_involvement","pace"],"agencyPoints":["Choose exam board version of questions","Tutor can extend exam practice phase","Sage silent during exam phase — full exam conditions"],"bestFor":"Year 10/11 students preparing for GCSE Higher who want exam technique + engagement"}',
 true, true),

-- 3. SEN Visual-First Relaxed Mastery
('sen-visual-first-mastery',
 'Visual-First Relaxed Mastery',
 'Step-by-step visual learning at your own pace. No timers, no pressure — pictures before algebra, encouragement at every step.',
 'Step-by-step visual learning at your own pace — no pressure, just understanding',
 '{"icon":"🌱","colour":"#10b981","backgroundStyle":"grid","narrative":"Every learner finds their own path through the forest. We''ll use pictures, diagrams, and as much time as you need. There''s no race — just growth."}',
 ARRAY['sen','visual','relaxed','any-topic','scaffolded','dyslexia','anxiety','any-level'],
 'any', 'any', 'SEN', 40, 'full', true,
 '[
   {"id":"check-in","name":"How Are You Feeling?","icon":"😊","durationMins":3,"sageMode":"full","sagePersona":"You are Sage, a calm and patient tutor. Never rush. Use short sentences. Never use more than 3 lines of text at once. Always ask ''Does that make sense so far?'' before moving on.","sagePromptTemplate":"Start with a gentle check-in: ''On a scale of 1-5, how confident do you feel about [topic] today?'' Based on their answer, adjust your pace and scaffolding. If they say 1-2, begin at the very beginning with a visual analogy.","canvasActions":[{"type":"set_background","backgroundStyle":"grid"}],"exitConditions":{"timeExpiredMins":5,"tutorOverride":true},"narrative":"We always start by checking how you feel. Your comfort matters most."},
   {"id":"visual-intro","name":"The Picture First","icon":"🖼️","durationMins":10,"sageMode":"full","sagePromptTemplate":"Introduce the concept using ONLY visual analogies and diagrams. Use the fraction bar, number line, or Venn diagram shape on the canvas. No algebraic notation until student shows they understand the visual. Ask after each step: ''Does this picture make sense?''","canvasActions":[{"type":"clear_canvas"},{"type":"stamp_shape","shape":"fraction-bar","position":"center"}],"exitConditions":{"sageSuggestsReady":true,"timeExpiredMins":15,"tutorOverride":true},"narrative":"Pictures before numbers. Always."},
   {"id":"guided-practice","name":"Try Together","icon":"🤝","durationMins":15,"sageMode":"co-teach","sagePromptTemplate":"Work through 2-3 problems TOGETHER with the student. Do the first one fully with them, narrating each step. Ask them to do step 1 of the second, then you do step 2, then they do step 3. Always praise attempt, never the result alone. Never say ''wrong'' — say ''almost, let''s look at this part together''.","canvasActions":[{"type":"clear_canvas"}],"exitConditions":{"minMasteryScore":50,"timeExpiredMins":18,"tutorOverride":true},"narrative":"We work through problems side by side — you''re never alone on this."},
   {"id":"independent","name":"Your Turn","icon":"⭐","durationMins":8,"sageMode":"hints","sagePromptTemplate":"Give ONE question the student can attempt alone. Provide a written hint card on the canvas listing the steps. Check in after 2 minutes: ''How''s it going? Want a smaller hint?'' Never let them feel stuck for more than 90 seconds without support.","canvasActions":[{"type":"clear_canvas"},{"type":"add_text","props":{"text":"Step hint card:\n1. Read the question\n2. Draw a picture first\n3. Try one step at a time","position":"top-right"}}],"exitConditions":{"tutorOverride":true,"timeExpiredMins":10},"narrative":"One question — all yours. The hint card is always there if you need it.","homeworkEnabled":true},
   {"id":"celebration","name":"Look How Far You''ve Come","icon":"🌟","durationMins":4,"sageMode":"full","sagePromptTemplate":"Celebrate what the student achieved today — be specific and genuine. Never compare to others. Mention one thing they understood that they didn''t at the start. Set a very small, achievable homework that feels like a continuation not a chore.","canvasActions":[],"exitConditions":{"tutorOverride":true,"timeExpiredMins":5},"narrative":"Every step forward matters. Let''s celebrate what you did today."}
 ]'::jsonb,
 '{"freedoms":["support","pace","ai_involvement"],"agencyPoints":["Sage always checks in before moving on — you control the pace","Visual-first: no algebra until you''re ready","Co-teach mode means you''re never working alone"],"bestFor":"Students with dyslexia, dyscalculia, exam anxiety, or anyone who learns best through pictures and encouragement"}',
 true, true),

-- 4. Quiet Diagnostic + Gap Fill Sprint
('quiet-diagnostic-gap-sprint',
 'Quiet Diagnostic + Gap Fill Sprint',
 'Fast, targeted diagnosis. 8 questions reveal the gaps; 15 minutes fix the most important one. Worksheet auto-generated at the end.',
 'Find the gaps, fix them fast — minimal AI, maximum efficiency',
 '{"icon":"🔍","colour":"#64748b","backgroundStyle":"default","narrative":"No story, no theme — just sharp, targeted diagnosis. Find exactly what needs fixing, then fix it."}',
 ARRAY['diagnostic','any-topic','gcse','a-level','11+','revision','exam-prep','efficient'],
 'any', 'any', 'any', 30, 'silent', false,
 '[
   {"id":"diagnostic","name":"Diagnostic","icon":"🔍","durationMins":12,"sageMode":"silent","sagePromptTemplate":"Give 8 rapid-fire questions across the topic, each worth 1 mark. Vary difficulty (4 easy, 3 medium, 1 hard). Record correct/incorrect. Do NOT give feedback during this phase. Calculate a skill map after all 8.","canvasActions":[{"type":"clear_canvas"}],"exitConditions":{"timeExpiredMins":15,"tutorOverride":true},"narrative":"8 quick questions. No hints, no feedback — just honest answers."},
   {"id":"gap-analysis","name":"Gap Analysis","icon":"📊","durationMins":5,"sageMode":"full","sagePromptTemplate":"Display a simple skill map: which questions correct, which wrong. Identify the 1-2 biggest gaps. Say: ''You have 15 minutes — we''re going to fix the most important gap right now.''","canvasActions":[{"type":"clear_canvas"},{"type":"add_text","props":{"text":"Your skill map 📊","position":"top-left"}}],"exitConditions":{"timeExpiredMins":5,"tutorOverride":true},"narrative":"See exactly where the gaps are — no guessing."},
   {"id":"targeted-fix","name":"Targeted Fix","icon":"🎯","durationMins":10,"sageMode":"co-teach","sagePromptTemplate":"Focus exclusively on the top 1-2 gaps identified. Teach the method concisely. Give 2 practice questions. Check understanding. No diversions.","canvasActions":[{"type":"clear_canvas"}],"exitConditions":{"minMasteryScore":70,"timeExpiredMins":12,"tutorOverride":true},"narrative":"15 minutes on the one thing that matters most.","homeworkEnabled":true},
   {"id":"worksheet-gen","name":"Generate Worksheet","icon":"📄","durationMins":3,"sageMode":"full","sagePromptTemplate":"Generate 5 practice questions focused on the gaps identified. These become the homework worksheet. Confirm with tutor before sending.","canvasActions":[],"exitConditions":{"tutorOverride":true,"timeExpiredMins":3},"narrative":"A targeted worksheet generated from YOUR specific gaps — not a generic sheet."}
 ]'::jsonb,
 '{"freedoms":["goal","pace"],"agencyPoints":["Completely tutor-led — Sage only speaks when useful","Worksheet auto-generated from your specific gaps","Fast — designed for 30-minute sessions"],"bestFor":"Exam-crunch revision or students who prefer a quiet, efficient session over a themed adventure"}',
 true, true),

-- 5. GCSE Full Paper Simulation
('gcse-full-paper-simulation',
 'GCSE Full Paper Simulation',
 'A full 60-minute timed mixed-topic practice paper in exam conditions, followed by mark-scheme teaching and a progress report.',
 '60-minute timed mixed-topic GCSE practice — exam conditions with mark-scheme debrief',
 '{"icon":"📝","colour":"#0f172a","backgroundStyle":"default","narrative":"This is as close to the real thing as it gets. Exam conditions, timed, no help. Then we go through every mark together."}',
 ARRAY['maths','gcse','exam','mixed-topic','timed','higher','foundation','year-11'],
 'any', 'maths', 'higher', 65, 'silent', false,
 '[
   {"id":"briefing","name":"Exam Briefing","icon":"📋","durationMins":3,"sageMode":"full","sagePromptTemplate":"Briefly explain exam conditions: no help from Sage, no calculator on Paper 1, show all working. Ask student to confirm they''re ready. Remind them: method marks are awarded even for wrong answers if working is shown.","canvasActions":[{"type":"clear_canvas"},{"type":"add_text","props":{"text":"📝 GCSE Paper Simulation — Exam Conditions","position":"top-left"}}],"exitConditions":{"tutorOverride":true,"timeExpiredMins":3},"narrative":"Exam conditions briefing. Read the rules, then we begin."},
   {"id":"paper","name":"Exam Paper","icon":"⏱️","durationMins":50,"sageMode":"silent","sagePromptTemplate":"Do not respond to any student questions during this phase. If asked for help, reply only: ''Exam conditions — I can''t help right now. Show your working and move on.'' The timer is running.","canvasActions":[{"type":"clear_canvas"},{"type":"add_text","props":{"text":"⏱️ 50 minutes — show all working","position":"top-left"}}],"exitConditions":{"timeExpiredMins":52,"tutorOverride":true},"narrative":"50 minutes. Show all working. Move on if stuck — come back at the end."},
   {"id":"mark-scheme","name":"Mark Scheme Walkthrough","icon":"✅","durationMins":10,"sageMode":"full","sagePromptTemplate":"Go through each question. For each: show the correct method, identify where method marks are awarded vs accuracy marks, explain common mistakes. If student got it right, confirm their method. If wrong, teach the correct approach concisely.","canvasActions":[{"type":"clear_canvas"}],"exitConditions":{"tutorOverride":true,"timeExpiredMins":12},"narrative":"Mark scheme time — every question, every mark explained."},
   {"id":"progress-report","name":"Progress Report","icon":"📊","durationMins":5,"sageMode":"full","sagePromptTemplate":"Give a summary: estimated grade based on marks, 2 strongest topics, 2 weakest topics, and 3 specific things to revise before the real exam. Be honest but encouraging.","canvasActions":[],"exitConditions":{"tutorOverride":true,"timeExpiredMins":5},"narrative":"Your honest progress report — where you are and exactly what to do next.","homeworkEnabled":true}
 ]'::jsonb,
 '{"freedoms":["goal","pace"],"agencyPoints":["Choose foundation or higher paper style","Tutor can pause paper for welfare check if needed","Mark-scheme teaching personalised to what you got wrong"],"bestFor":"Year 11 students in the final weeks before GCSE exams who need to practise under real conditions"}',
 true, true);
