name: = Bug Report
description: Report a bug or issue with Tutorwise
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in Tutorwise! Please fill out this template to help us understand and reproduce the issue.

  - type: checkboxes
    id: confirmation
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have tested this on the latest version of Tutorwise
          required: true
        - label: I can reproduce this issue consistently
          required: false

  - type: textarea
    id: bug-description
    attributes:
      label: = Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: = Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label:  Expected Behavior
      description: What you expected to happen
      placeholder: "Expected behavior..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: L Actual Behavior
      description: What actually happened instead
      placeholder: "Actual behavior..."
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: =d User Type
      description: What type of user were you when encountering this bug?
      options:
        - Student
        - Tutor
        - Agent
        - Admin
        - Anonymous/Guest
        - Other
    validations:
      required: true

  - type: dropdown
    id: bug-category
    attributes:
      label: =Â Bug Category
      description: Which area of Tutorwise does this bug affect?
      options:
        - Authentication (Login/Signup)
        - Dashboard
        - Payment Processing
        - TestAssured Platform
        - Booking System
        - User Profile
        - Navigation
        - Mobile Experience
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: =¨ Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable, blocking core functionality)
        - High (Major feature broken, significant impact)
        - Medium (Minor feature issue, workaround available)
        - Low (Cosmetic issue, minimal impact)
    validations:
      required: true

  - type: textarea
    id: browser-info
    attributes:
      label: < Browser & Device Information
      description: Please provide browser and device details
      placeholder: |
        - Browser: Chrome 118
        - OS: macOS 14.0
        - Device: MacBook Pro M2
        - Screen Resolution: 1920x1080
        - Mobile/Desktop: Desktop
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: = Console Errors
      description: Any errors in browser console? (Press F12 ’ Console tab)
      placeholder: "Paste console errors here..."
      render: javascript

  - type: textarea
    id: network-errors
    attributes:
      label: < Network Errors
      description: Any failed network requests? (Press F12 ’ Network tab)
      placeholder: "Paste network errors here..."

  - type: textarea
    id: additional-context
    attributes:
      label: =Ý Additional Context
      description: Any other context, screenshots, or information
      placeholder: "Additional details..."

  - type: checkboxes
    id: tested-environments
    attributes:
      label: >ê Tested Environments
      description: Where have you confirmed this bug occurs?
      options:
        - label: Production (tutorwise.vercel.app)
        - label: Local development
        - label: Mobile browser
        - label: Desktop browser
        - label: Incognito/Private mode

  - type: markdown
    attributes:
      value: |
        ---
        **=' For Developers:**
        - Check TestAssured monitoring for related issues
        - Review E2E test results for similar failures
        - Consider adding test coverage for this scenario