name: ( Feature Request
description: Suggest a new feature or enhancement for Tutorwise
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature for Tutorwise! Your ideas help us build a better tutoring platform.

  - type: checkboxes
    id: confirmation
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have reviewed the current roadmap to see if this is planned
          required: true
        - label: This feature aligns with Tutorwise's mission of connecting tutors and students
          required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: <¯ Feature Summary
      description: A clear and concise description of the feature
      placeholder: "Briefly describe the feature..."
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: =d Primary User Type
      description: Which user type would benefit most from this feature?
      options:
        - Student
        - Tutor
        - Agent
        - Admin
        - All Users
        - System/Developer
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: =Â Feature Category
      description: Which area of Tutorwise would this feature enhance?
      options:
        - Dashboard & UI
        - Booking & Scheduling
        - Payment & Billing
        - Communication
        - Search & Discovery
        - Profile Management
        - Analytics & Reporting
        - Mobile Experience
        - API & Integration
        - Testing & Quality
        - Security
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: = Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        - What challenge are users currently facing?
        - Why is this important?
        - How does it impact the user experience?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: =¡ Proposed Solution
      description: Detailed description of the feature you'd like
      placeholder: |
        - How would this feature work?
        - What would the user interface look like?
        - What are the key interactions?
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: =Ö User Stories
      description: Write user stories for this feature
      placeholder: |
        As a [user type], I want [goal] so that [benefit].

        Examples:
        - As a student, I want to filter tutors by subject so that I can find relevant help quickly.
        - As a tutor, I want to set my availability in advance so that students can book appropriate time slots.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: =€ Priority Level
      description: How important is this feature?
      options:
        - Critical (Core functionality, blocks user goals)
        - High (Significant value, improves key workflows)
        - Medium (Nice to have, enhances experience)
        - Low (Minor improvement, future consideration)
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label:  Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
        - [ ] Mobile responsive
        - [ ] Accessible (WCAG compliant)
        - [ ] Tested across browsers

  - type: textarea
    id: additional-context
    attributes:
      label: =Ý Additional Context
      description: Any other context, references, or examples
      placeholder: |
        - Similar features in other platforms?
        - Research or data supporting this?
        - Timeline requirements?