/**
 * Growth Marketplace Agent
 *
 * User-created Growth Agents — business coaching agents sold in the marketplace.
 * Extends MarketplaceAIAgent. Created in AI Studio, published after subscription.
 *
 * Key difference from GrowthPlatformAgent:
 * - NO access to buyer's private Tutorwise data (bookings, revenue, referrals)
 * - Strategy/advice ONLY — based on owner's uploaded playbooks and knowledge
 * - Owner uploads: frameworks, templates, playbooks, checklists
 * - Buyer subscribes: £ set by creator
 *
 * Example use cases:
 * - "UK Tutor Business Scaling Playbook" (upload: PDF guide, templates)
 * - "GCSE Maths Tutor Growth Coach" (upload: subject-specific strategy)
 * - "Referral Agency Blueprint" (upload: agency-building frameworks)
 *
 * @module growth/agents
 */

import { MarketplaceAIAgent } from '@sage/agents/MarketplaceAIAgent';
import type { BaseAIAgent, AgentConfig } from '@sage/agents/base/types';

// GrowthMarketplaceAgent uses MarketplaceAIAgent as-is.
// The key customisation is in agent_type: 'growth_advisor' and the
// system prompt generated by the owner during agent creation.
//
// This class exists as a named export for clarity and future customisation.
// No method overrides needed — MarketplaceAIAgent's RAG + Gemini flow works correctly.

export class GrowthMarketplaceAgent extends MarketplaceAIAgent {
  constructor(agent: BaseAIAgent, config: AgentConfig) {
    if (agent.agent_type !== 'growth_advisor') {
      throw new Error('GrowthMarketplaceAgent requires agent_type: growth_advisor');
    }
    super(agent, config);
  }
}

export default GrowthMarketplaceAgent;
